server:
  port: 9090

spring:
  datasource:
#    url: jdbc:mysql://192.168.0.238:3306/local_station?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://192.168.0.11:3306/testSpringboot?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://127.0.0.1:3335/local_station?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/local_station?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://119.3.42.30:53306/local_station?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 127.0.0.1
    port: 6378
    #password: ENC(+yGpfuuKZ1uMmkwnU/Pho8TDZJL3OdjA)
    timeout: 1000ms
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
        max-active: 8

  rabbitmq:
      host: localhost
      port: 5673
      username: rabbitmq
      password: 29G8CSIDJz$K
  servlet:
    multipart:
      enabled: true
      #单个文件大小限制
      max-file-size: 20MB
      #单个请求总的大小限制
      max-request-size: 200MB

#加载Mybatis映射文件
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.producehelper.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    cache-enabled: false
    map-underscore-to-camel-case: true
    local-cache-scope: statement
  global-config:
    db-config:
      id-type: auto

#数据库加密
jasypt:
  encryptor:
    password: zhnyxs

logging:
  level:
    org.springframework.web: INFO
    com.xingyi.pos: INFO

file:
  sqlLogFile: test.log
  dataSourceFile: config/测试站点信息.xlsx
